### ISSUE TITLE
Add BLOG page...

### ISSUE THREAD

**Issue by dbarrundiag** [florianhauer/GTTriathlon_Website#14]
Flo can you check if this works in a Dummy Page:
iframe width="420" height="315" src="https://gttriathlon.wordpress.com/" frameborder="0" allowfullscreen

(add '<' before iframe and close it </iframe> )

**Comment by dbarrundiag** [comment]
Flo do you think you can do this? I know this is a way better way to integrate the blog that the iframe which it sucks! if you can't we'll just leave it with the iframe:
http://codex.wordpress.org/Integrating_Wordpress_with_Your_Website

the wordpress page is this one: gttriathlon.wordpress.com

**Comment by florianhauer** [comment]
we will the iframe solution

the php solution is complex and requires to have wordpress installed locally, it doesn't work when hosted on wordpress.com
